### ISSUE TITLE
No file named `docs_filter.tsv`

### ISSUE THREAD

**Issue by jordane95** [yflyl613/Tiny-NewsRec#2]
Hi,

I want to run the pretraining part in your jupyter [notebook](https://github.com/yflyl613/Tiny-NewsRec/blob/main/Domian-specific_Post-train.ipynb), but find that the pretraining data is not prepared...

May I know how you construct the `docs_filter.tsv` file? Thanks.

**Comment by yflyl613** [comment]
> Hi,
> 
> I want to run the pretraining part in your jupyter [notebook](https://github.com/yflyl613/Tiny-NewsRec/blob/main/Domian-specific_Post-train.ipynb), but find that the pretraining data is not prepared...
> 
> May I know how you construct the `docs_filter.tsv` file? Thanks.

I'm sorry I could not provide the `docs_filter.tsv` used in our experiments. It is collected from the Microsoft News corpus during my internship at Microsoft. Actually, I think you can use other public news corpus instead. For example, you may try to use the news articles provided with the [MIND](https://msnews.github.io/) dataset for pre-training.
