### ISSUE TITLE
the dataset cannot be read normally

### ISSUE THREAD

**Issue by XiaoLongtaoo** [yflyl613/Tiny-NewsRec#4]
During the fine-tuning phase, due to the lack of multiple GPUs in our lab, I have commented out all Horovod-related code in the distributed training code. Under these circumstances, when running ./demo.sh train in the PLM-NR folder, I encounter a situation where ![code](https://github.com/yflyl613/Tiny-NewsRec/assets/90383205/61bcf12f-3628-4f59-a612-3dd532c7154b) (it cannot read data normally for several hours without any error messages; if this is normal, please let me know).

Do you have a complete runnable code or any other feasible solutions? My current guess is that this issue might be caused by multi-threaded reading or commenting out parts of the distributed training code.

**Comment by yflyl613** [comment]
> During the fine-tuning phase, due to the lack of multiple GPUs in our lab, I have commented out all Horovod-related code in the distributed training code. Under these circumstances, when running ./demo.sh train in the PLM-NR folder, I encounter a situation where ![code](https://user-images.githubusercontent.com/90383205/268502221-61bcf12f-3628-4f59-a612-3dd532c7154b.jpg) (it cannot read data normally for several hours without any error messages; if this is normal, please let me know).
> 
> Do you have a complete runnable code or any other feasible solutions? My current guess is that this issue might be caused by multi-threaded reading or commenting out parts of the distributed training code.

Reading data for several hours is definitely abnormal. There may be something wrong when you commented out all the Horovod-related codes. If you don't want to use multiple GPUs, you can simply set the parameter `enable_hvd` as `False` in `demo.sh`. Then the entire process should run on a single GPU.

**Comment by XiaoLongtaoo** [comment]
Thank you, your code needs some slight modifications to work properly in `tf2.0`. My issue has been resolved. There is no `enable_hvd` parameter in the `demo.sh` file; this parameter needs to be set in `parametes.py`

**Comment by XiaoLongtaoo** [comment]
It seems that during the fine-tuning stage of the teacher model, the code in run.py needs to be modified as shown in the following diagram, otherwise, it will be unable to load the pre-training phase model parameters.
![1](https://github.com/yflyl613/Tiny-NewsRec/assets/90383205/361c62af-144f-4252-a782-70ac5d175300)

**Comment by yflyl613** [comment]
> It seems that during the fine-tuning stage of the teacher model, the code in run.py needs to be modified as shown in the following diagram, otherwise, it will be unable to load the pre-training phase model parameters. ![1](https://user-images.githubusercontent.com/90383205/268627701-361c62af-144f-4252-a782-70ac5d175300.png)

Yes, that's right. You can just comment out Line 63-64 in `run.py` when fine-tuning the teacher model. These two lines should be set when performing the Stage II knowledge distillation on the student model. Thanks for pointing this out.
